apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    component: backend
    project: expense
    tier: app
spec:
  replicas: 2
  selector:
    matchLabels:
      component: backend
      project: expense
      tier: app
  template:
    metadata:
      labels:
        component: backend
        project: expense
        tier: app
    spec:
      containers:
        - name: backend
          image: 324037294108.dkr.ecr.us-east-1.amazonaws.com/expense-backend:<version> # Specify your image version here
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: backend
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi" # Minimum memory requested
              cpu: "100m" # Minimum CPU requested
            limits:
              memory: "512Mi" # Maximum memory limit
              cpu: "200m" # Maximum CPU limit
