kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  namespace: expense
  labels:
    component: backend
    project: expense
    tier: app
spec:
  replicas: { { .Values.deployment.replicas } } # Corrected without spaces
  selector:
    matchLabels:
      component: backend
      project: expense
      tier: app
  template:
    metadata:
      labels:
        component: backend
        project: expense
        tier: app
    spec:
      containers:
        - name: backend
          imagePullPolicy: Always
          image: 324037294108.dkr.ecr.us-east-1.amazonaws.com/expense-backend:{{ .Values.deployment.imageVersion }} # Corrected without spaces
          envFrom:
            - configMapRef:
                name: backend
